name: 'Setup Java & Gradle'
runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5
      with:
        distribution: 'zulu'
        java-version: '25'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5