name: 'Setup Java & Gradle'
runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5
      with:
        distribution: 'liberica'
        java-version: '25'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6