name: 'Setup Java & Gradle'
runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5
      with:
        distribution: 'liberica'
        java-version: '25'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6