name: 'Setup Java & Gradle'
runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5
      with:
        distribution: 'liberica'
        java-version: '25'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6